name: android_foreground_service_with_awesome_notifications_example
description: Demonstrates how to use the android_foreground_service_with_awesome_notifications plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.0.6+9
  android_foreground_service_with_awesome_notifications:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true